version: "3.8"
services:
  ide:
    image: docker.packages.nuxeo.com/nos-dev/shell-project:latest
    command: tail -f /dev/null
    user: "<%= process.getuid() + ':' +  process.getgid() %>"
    tty: true
    volumes:
      # Shell Project Config
      - ../.env.nuxeo-cli:/home/nuxeo/workspace/.env.nuxeo-cli
      # VSC Tasks and scripts related
      - ../.vscode:/home/nuxeo/workspace/.vscode
      # Local repository
      - ..:/home/nuxeo/workspace/<%= global._options.dirname %>
      # M2 repository
      - m2repo:/home/nuxeo/.m2/repository
      # VSCode installed extensions cache
      - vscode-extensions:/home/nuxeo/.vscode-server/extensions
      - vscode-extensions:/home/nuxeo/.vscode-server-insiders/extensions
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Nuxeo CLI configuration
      - ../.yo-rc.json:/home/nuxeo/workspace/.yo-rc.json
volumes:
  vscode-extensions: {}
  m2repo: {}
